name: moniewatch

on:
 # determines the branch we are working on
 # we are working on the staging branch
 push:
    branches:
      - "staging"
 pull_request:
   branches:
     - "master" 
   paths:
     - ".github/workflows/integration.yml"
      
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
 
jobs:
 build-backend:
  runs-on: ubuntu-latest
  defaults:
   run:
    working-directory: MonieWatch/backend
    
  steps:
      - name: pulls code from github repo
        uses: actions/checkout@v2

      - name: Set up python:3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'pip'
      
      
      -  uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt; fi
